config.robot = {
	"socket" : null,
	"map_head_id" : null,
	"areaCleanFlag" : null,
	"workMode" : null,
	"battary" : null,
	"chargeStatus" : null,
	"type" : null,
	"faultCode" : null,
	"cleanPerference" : null,
	"repeatClean" : null,
	"cleanTime" : null,
	"cleanSize" : null,
	"waterlevel" : null,
	"dustBox_type" : null,
	"mop_type" : null,
	"house_name" : null,
	"map_count" : null,
	"current_map_name" : null,
	"cleaning_roomId" : null,
	"did" : null,
	"targets" : null,
	"clientType" : null,
	"lock_device": false,
	"going_to_dock": false,
	"versions" : null,
	"mac": null,
	"sn": null,
	"projectType" : null,
	"bindtime" : null,
	"ctrTime" : null
}
